"""
Django settings for XSearch project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 支持环境变量覆盖，生产环境务必设置 DJANGO_SECRET_KEY
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", '5)$op9fxf2b#%(*_-qcr7sf)*c@gr!v=d851(*3f*2gef0f!#d')

# SECURITY WARNING: don't run with debug turned on in production!
# 支持环境变量覆盖：DJANGO_DEBUG=false 关闭调试模式
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

# 允许的主机名，支持环境变量覆盖（逗号分隔），生产环境务必设置
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# ---------- 生产环境安全配置（DEBUG=False 时自动启用） ----------
if not DEBUG:
    # HTTPS 相关配置：仅在站点确实部署在 HTTPS 之后开启（常见 docker-compose
    # 链路是纯 HTTP 的 nginx 反代，开启会导致 Cookie 不发送/HSTS 拒绝访问）
    # SECURE_SSL_REDIRECT = True
    # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # SECURE_HSTS_SECONDS = 31536000  # 1 年
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True

    # Cookie 安全（任何部署形态都建议开启）
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

    # 其他安全头
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # 生产环境强制要求 ALLOWED_HOSTS 非空
    if not ALLOWED_HOSTS:
        import sys
        print("⚠️  生产环境（DEBUG=False）必须设置 DJANGO_ALLOWED_HOSTS 环境变量！")
        print("   示例：export DJANGO_ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com")
        sys.exit(1)

    # 生产环境警告：SECRET_KEY 使用默认值
    if SECRET_KEY == '5)$op9fxf2b#%(*_-qcr7sf)*c@gr!v=d851(*3f*2gef0f!#d':
        print("⚠️  警告：生产环境使用了默认 SECRET_KEY，请设置 DJANGO_SECRET_KEY 环境变量！")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'search',
]

MIDDLEWARE = [
    'xsearch.middleware.CorsMiddleware',  # 白名单式 CORS：前端独立部署跨域调用 /api/*
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 允许跨域的前端来源（开发态 Vite 默认 5173；也可用环境变量 FRONTEND_ORIGINS 追加）
CORS_ALLOW_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:4173",   # vite preview
    "http://127.0.0.1:4173",
]

ROOT_URLCONF = 'xsearch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 页面层已由 frontend/ Vue 工程承担，这里仅保留 Django admin 所需配置
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xsearch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# ---------- Elasticsearch 配置（支持环境变量覆盖） ----------
ES_URL = os.getenv("ES_URL", "http://127.0.0.1:9200")
ES_INDEX = os.getenv("ES_INDEX", "quotes")

# ---------- Redis 配置（支持环境变量覆盖） ----------
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")

# ---------- API 鉴权（可选） ----------
# 设置后写操作接口（爬虫启动/定时任务/评论抓取）与 AI 问答接口要求请求头
# X-API-Token 匹配；留空表示不启用（本机开发态默认开放）
API_TOKEN = os.getenv("API_TOKEN", "")

# ---------- 管理员账号（「采集管理」页登录） ----------
# 优先读环境变量，再由 XSearch/local_settings.py（已 gitignore，严禁提交）覆盖；
# 两者都未配置时登录接口直接拒绝，采集管理不可用
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "")

_local_settings = os.path.join(BASE_DIR, "local_settings.py")
if os.path.exists(_local_settings):
    # 在模块全局命名空间中执行，覆盖上面的默认值
    exec(compile(open(_local_settings, encoding="utf-8").read(),
                 _local_settings, "exec"), globals())

# ---------- 日志 ----------
# 让 search 应用的 INFO 日志（调度器启动/任务清理等）输出到控制台；
# 默认配置下非 django logger 的 INFO 会被丢弃，重启后看不到调度器启动记录
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "[{asctime}] {levelname} {name}: {message}",
                   "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "loggers": {
        "search": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}